# Generated by Django 4.2.5 on 2024-08-13 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='titel',
            new_name='title',
        ),
    ]
