# Generated by Django 4.2.5 on 2024-08-14 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_rename_titel_room_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='messages',
            field=models.ManyToManyField(blank=True, null=True, to='chat.message'),
        ),
    ]
